### ISSUE TITLE
ADSTS28003: Provided value for the input parameter scope cannot be empty when requesting an access token using the provided authorization code

### ISSUE THREAD

**Issue by nrvana** [AzureAD/microsoft-authentication-library-for-python#125]
I am experiencing an error in my app telling me that my scope is empty, however, the scopes I am using and consented to are "scopes: offline_access openid profile https://management.azure.com/user_impersonation https://*.dfs.core.windows.net/user_impersonation" 

```
InvalidClientIdError at /app/callback

(invalid_request) AADSTS28003: Provided value for the input parameter scope cannot be empty when requesting an access token using the provided authorization code. Please specify a valid scope.
Trace ID: 42ffbfa1-14ea-4ef8-808e-eabf580e9200
Correlation ID: 0e34807f-6b37-4501-8169-412797925bcd
Timestamp: 2019-11-11 16:29:41Z
```

After doing some searching, it appears that an android user got the same error in this issue for the android library: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/652

The commit for the fix had the comment:
```
            /*
            ===============================================================
            NOTE: When requesting tokens for resources other than MS Graph or AAD Graph the default scopes
            openid, profile and offline_access are not returned.  They need to be written into the cache anyway
            to avoid cache misses.
            ===============================================================
             */
```

I was wondering if the same bug was present in the python implementation and could be fixed in a similar manor.

Thanks

**Comment by rayluo** [comment]
Did you encounter suhc error in the response of your [`acquire_token_by_authorization_code()` call](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.acquire_token_by_authorization_code)? If so, what did you provide as its scopes parameter? It is supposed to be a required parameter.

What would be the result, if you feed the scopes parameter with:
* Both `["https://management.azure.com/user_impersonation", "https://*.dfs.core.windows.net/user_impersonation"]`
* Just `["https://management.azure.com/user_impersonation"]`
* or just `["https://*.dfs.core.windows.net/user_impersonation"]`?

**Comment by nrvana** [comment]
Hi Ray,

In the tutorial I borrowed the code from the error occurs in the fetch_token call on this line: https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/master/Demos/02-add-aad-auth/graph_tutorial/tutorial/auth_helper.py#L40

After testing the three scenarios you posted, it seems that I need to use https://storage.azure.com as opposed to https://*.dfs.core.windows.net, but the results were:

- Both management and storage: error AADSTS28003
- Just management: token is created without error
- Just storage: token is created without error

Thanks
Brian

**Comment by rayluo** [comment]
Oh Brian, that sample you were referring to, [is using a 3rd-party auth library](https://github.com/microsoftgraph/msgraph-training-pythondjangoapp/blob/master/Demos/02-add-aad-auth/graph_tutorial/tutorial/auth_helper.py#L2). We might not be able to provide too much troubleshooting down the road on that direction. If you would like to give this MSAL library a shot, we do provide an [MSAL web app sample implemented with Flask](https://github.com/Azure-Samples/ms-identity-python-webapp).

Now back to your original question. In Microsoft identity platform, you can:

1. have the end user consent to scopes of multiple resources A & B and get back an authorization code,
2. But then when redeeming such code, you can only specify one specific resource, say resource A, because the issued access token would only be used with one resource A anyway.
3. Later when you need an access token for resource B, you would need to acquire a different access token for resource B. (By the way, at this point the authorization code obtained in step 1 might have been expired - in fact it was not mean to be reused anyway - so do you need to trigger the consent again? No, you don't have to. This is where the MSAL Python comes into play. You just call its `acquire_token_silent(scopes=["B"])`, and it would use a refresh token came back from step 2 (if any), to obtain a new access token for resource B, without user interaction.)

**Comment by nrvana** [comment]
Ah, my misunderstanding. Thank you for the additional info, it's really helpful and makes sense.
