### ISSUE TITLE
token cache: make it extensible to persist extra information 

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-library-for-python#14]
We can brainstorm more on this, but for service principal authentication, it is inevitable to save the secret; otherwise, any long running process (1+ hour) will not work, because client secret/assertion flow has no refresh tokens. 
Since all those data are related, it would be great we have one data structure to save both of them

**Comment by marstr** [comment]
This would be a great feature. @cormacpayne (Azure PowerShell), @zezha-msft (Azure Storage), and I (Azure CLI) have had brief conversations about how all of us would like to securely store Service Principal credentials. Moving it upstream into these MSAL libraries would a be a huge boon for all of our projects.

**Comment by rayluo** [comment]
This issue has been open for quite some time. We would like to close it by saying:

* The MSAL token cache format has actually been designed to be extensible from day 1.
* MSAL will probably not provide out-of-box support for storing service principals. You can roll your own, and ideally store it into a different physical file, so that it won't mix with MSAL's own cache data. And you can still benefit from the encryption and concurrency control provided by upcoming MSAL Extensions module. The major part of the recipe looks like this.

```python
class ServicePrincipalStorage(msal.TokenCache):
    SP_NAMESPACE = "ServicePrincipal"  # Choose a namespace not conflicting with MSAL
    def __init__(self):
        super(ServicePrincipalStorage, self).__init__()
        self.key_makers[self.SP_NAMESPACE] = lambda client_id=None, **kwargs: client_id  # magic
    ...
```
