### ISSUE TITLE
device_flow_sample.py no longer works

### ISSUE THREAD

**Issue by clreinki** [AzureAD/microsoft-authentication-library-for-python#141]
After creating the app registration and attempting to run device_flow_sample.py (with config.json containing the tenant-specific appid), device_flow_sample.py returns the following error:

Traceback (most recent call last):
  File "sample_azure.py", line 62, in <module>
    "Fail to create device flow. Err: %s" % json.dumps(flow, indent=4))
ValueError: Fail to create device flow. Err: {
    "error": "invalid_request",
    "error_description": "AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 2427820b-55d9-4be8-943a-1497c349f200\r\nCorrelation ID: e561c394-c4e3-4c43-be57-b35e3070cac5\r\nTimestamp: 2020-01-06 20:50:25Z",
    "error_codes": [
        50059
    ],

**Comment by rayluo** [comment]
Hi @clreinki , thanks for your interest in using MSAL Python!

[Device Flow requires minimal configuration to start: a client_id and an authority url](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.0.0/sample/device_flow_sample.py#L36). Would you mind to double check your configuration? The default [placeholder client_id](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.0.0/sample/device_flow_sample.py#L6) in our sample is NOT a real client_id so it would indeed cause an AADSTS50059 error.

If you still see such error, we would probably need your client_id and authority configuration to reproduce this from our end, and investigate. (Those two info are not considered as confidential, but if you don't feel comfortable to share it here, you can email it to @navyasric , @abhidnya13 and me (@rayluo ) so that we will follow up.)

**Comment by clreinki** [comment]
Yes, I just happened to figure it out a little bit ago.  I had my client_id in there but I didn't realize I needed to append my domain name to the authority url.  After I did that, it worked great.  Thank you!

PS I'm excited for interactive username/password authentication with MFA support to come to MSAL Python!
