### ISSUE TITLE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443

### ISSUE THREAD

**Issue by geoffroygivry** [AzureAD/microsoft-authentication-library-for-python#172]
Hi all, 
First of all, a small disclaimer, I am not a web developer, so I do apologize in advance if this issue has been discussed before or by the stupidity of this question. 

I've used the username_password_sample.py to try to connect to get the token access to use Microsoft graph. but it looks like the provided Authority URL or the URL finishing with either the tenant ID or the tenant name doesn't connect at all and I have this warning message:
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /organizations/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1405`
Correct me if I'm wrong, but it looks like the authority URL is not valid? 
Thanks a lot for your help!

**Comment by rayluo** [comment]
Welcome @geoffroygivry !

First of all, you do not need to be a web developer to start using MSAL library and Microsoft identity platform. Our technology is open for everyone. :-)

That "warning message" you quoted, was not a warning, it was a DEBUG message. So that message itself did not imply anything had went wrong. If you see some other more specific error message after that line, feel free to share it here.

By the way, assuming you are using our username_password_sample.py from this repo, make sure you also read [this wiki page highlighted here](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.1.0/sample/username_password_sample.py#L55-L56). Many common errors caused by known constraints have been described there.

PS: CCing our PM @navyasric in case there would be any follow-up needed for this issue.

**Comment by geoffroygivry** [comment]
Hi Ray, many thanks for your warm welcome and your precious help, this is much appreciated!

I've read most of the documentation and I've registered my application and it is working very well with the application API permissions.
Now my goal is to send from a VFX software (Foundry's Nuke) a message into Teams. The permission for this needs to be a Delegated permission using ['Group.ReadWrite.All']. So I guess I should authenticate with my login to get the access token right? I don't want to use a web app like Flask to authenticate, the json file with credentials is more than enough in my case.

By using the  username_password_sample.py, what I don't understand is that the authority URL returns a code 443 with this URL. (https://login.microsoftonline.com/organizations or https://login.microsoftonline.com/<tenant_ID> or https://login.microsoftonline.com/<tenant_name>)
Does it mean it is not the right URL?

As well when I perform the result it returns this:
```invalid_client
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: d037f4f5-c276-4a14-9590-bdd3a3305301
Correlation ID: e7cf004e-6055-46ab-b87f-206fd2d6ade9
Timestamp: 2020-03-17 19:25:47Z
e7cf004e-6055-46ab-b87f-206fd2d6ade9```

So I believe that my parameters.json are wrongly setup, but I can't find the issue there.
Again thank you so much for your help and your time Ray! :)

**Comment by rayluo** [comment]
Hi Geoffroy, I believe you missed out this step during app registration.

![setup_public_app](https://user-images.githubusercontent.com/821550/76988648-4499c280-6902-11ea-8be5-00292624a274.png)

which is vaguely mentioned as "6. Then set the Default Client Type to Yes and Save." in this sample. Were you following [this sample](https://github.com/Azure-Samples/ms-identity-python-desktop/tree/master/1-Call-MsGraph-WithUsernamePassword)?

I'm about to also add this screenshot into the wiki page I mentioned earlier.

**Comment by geoffroygivry** [comment]
Ray, you are a Hero! That is working very well! Thanks a lot for this and sorry for not having read as much the documentation as I've should have done! :)
