### ISSUE TITLE
Change useragent ?

### ISSUE THREAD

**Issue by fldu** [AzureAD/microsoft-authentication-library-for-python#189]
Hello,

I'm currently trying to integrate a different user-agent

Currently, this code is working perfectly:
```
app.acquire_token_by_username_password(
                    config["username"], config["password"], scopes=config["scope"], proxies=my_proxy)
```
However, when I try to add something like:
```
app.acquire_token_by_username_password(
                    config["username"], config["password"], scopes=config["scope"], proxies=my_proxy, headers = {'User-agent': 'My user-agent'})
```
I obtain:
```
obtain_token_by_username_password() got multiple values for keyword argument 'headers'
```
Has someone an idea on how to solve that problem ?

Thanks

**Comment by rayluo** [comment]
Interesting topic.

"Supporting customizable headers" was never one of the [features we documented (thus promised)](https://msal-python.readthedocs.io/en/latest/?badge=latest), although MSAL could/might provide that behaivor as a happy by-product. At this point, we can not promise we will add such behavior (back), because we want to discourage your dependency on any undocumented behavior.

Out of curiosity, why would you want to "integrate a different user-agent" in the first place? As far as I know, Microsoft identity servers do not restrict any user-agent. If you were just trying identify your app to Microsoft, you can opt in to use a `app_name` parameter provided since [MSAL Python 1.1.0](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.1.0).

**Comment by fldu** [comment]
I was testing the library and "playing" a bit with Azure logs.

Thanks for your answer, I'll use the ```app_name``` option.
