### ISSUE TITLE
MS Personal account,OneNote Personal and Python script using device authentication flow

### ISSUE THREAD

**Issue by 1001QAdotNET** [AzureAD/microsoft-authentication-library-for-python#194]
Hi guys

Could you please tell me what I am doing wrong?
Full case description here: https://stackoverflow.com/questions/61803191/what-type-of-app-authentication-flow-should-i-select-to-read-my-onenote-content  
If needed I can copy and paste the content here
I think it all boils down to this  error message. I might be pretty close to solving my problem
Am I doing it wrong ? If not what are the /consumer endpoints that I should use in order to read my OneNote content via a Python script run from the command line?

```
Fail to create device flow. Err: {
    "error": "invalid_request",
    "error_description": "AADSTS9002331: Application 'bbd3d6df-f5f3-4206-8bd5-xxxxxxxx ' (OneNotePersonal) is configured for use by Microsoft Account users only. Please use the **/consumers endpoint** to serve this request.\r\nTrace ID: 1c4047e6-98a8-4615-9a0c-4b0dc9ba5600\r\nCorrelation ID: a6733520-6df9-422a-a6b4-e8f4e2de1265\r\nTimestamp: 2020-05-14 16:56:27Z",
    "error_codes": [
        9002331
    ],
    "timestamp": "2020-05-14 16:56:27Z",
    "trace_id": "1c4047e6-98a8-4615-9a0c-4b0dc9ba5600",
    "correlation_id": "a6733520-6df9-422a-a6b4-e8f4e2de1265",
    "interval": 5,
    "expires_in": 1800,
    "expires_at": 1589477187.9909642,
    "_correlation_id": "a6733520-6df9-422a-a6b4-e8f4e2de1265"
}
```

thank you

**Comment by rayluo** [comment]
Welcome @1001QAdotNET.

I agree that "Please **use the /consumers endpoint** to serve this request" error message (which can also be found [here](https://login.microsoftonline.com/error?code=9002331)) is vague. (@navyasric can we relay this feedback to proper team to fix it?)

@1001QAdotNET , to answer your question here. That error message suggests you to create your authority string as `authority = "https://login.microsoftonline.com/consumers"`, because you were using the client_id of a "personal app". Change that authority, and you can proceed. However, you may (or may not) encounter next error, because Device Flow may not work with Microsoft Personal Accounts. Try it out, and let us know, we will go from there. Our PM @navyasric and us will be happy to help.

PS: There are several [account types](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-supported-account-types).

**Comment by 1001QAdotNET** [comment]
Yes I got this
`To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 6PHXV4M7 to authenticate.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
c:\Users\xxx\Documents\VSCode\DevAsocCode\msal_device_flow.py in 
     21 print(flow["message"])
     22 
---> 23 result = app.acquire_token_by_device_flow(flow)

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\application.py in acquire_token_by_device_flow(self, flow, **kwargs)
    722                     self.ACQUIRE_TOKEN_BY_DEVICE_FLOW_ID),
    723                 },
--> 724             **kwargs)
    725 
    726     def acquire_token_by_username_password(

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\oauth2cli\oauth2.py in obtain_token_by_device_flow(self, flow, exit_condition, **kwargs)
    278         """
    279         while True:
--> 280             result = self._obtain_token_by_device_flow(flow, **kwargs)
    281             if result.get("error") not in self.DEVICE_FLOW_RETRIABLE_ERRORS:
    282                 return result

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\oauth2cli\oauth2.py in _obtain_token_by_device_flow(self, flow, **kwargs)
    241             })
    242         result = self._obtain_token(
--> 243             self.DEVICE_FLOW["GRANT_TYPE"], data=data, **kwargs)
    244         if result.get("error") == "slow_down":
    245             # Respecting https://tools.ietf.org/html/draft-ietf-oauth-device-flow-12#section-3.5

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\oauth2cli\oidc.py in _obtain_token(self, grant_type, *args, **kwargs)
     81         whose value will be a dictionary returned by :func:`~decode_id_token`.
     82         """
---> 83         ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
     84         if "id_token" in ret:
     85             ret["id_token_claims"] = self.decode_id_token(ret["id_token"])

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\oauth2cli\oauth2.py in _obtain_token(self, grant_type, params, data, *args, **kwargs)
    397         refresh_token = _data.get(RT)
    398         resp = super(Client, self)._obtain_token(
--> 399             grant_type, params, _data, *args, **kwargs)
    400         if "error" not in resp:
    401             _resp = resp.copy()

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\msal\oauth2cli\oauth2.py in _obtain_token(self, grant_type, params, data, headers, timeout, post, **kwargs)
    155             **kwargs)
    156         if resp.status_code >= 500:
--> 157             resp.raise_for_status()  # TODO: Will probably retry here
    158         try:
    159             # The spec (https://tools.ietf.org/html/rfc6749#section-5.2) says

C:\Utils\WinPython64-3.7.4.1\WPy64-3741\python-3.7.4.amd64\lib\site-packages\requests\models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

**HTTPError: 503 Server Error: Service Unavailable for url: https://login.microsoftonline.com/consumers/oauth2/v2.0/token`**

**Comment by 1001QAdotNET** [comment]
I am quite sure this is not the best way to do it but I am am out of ideas
What is a recommended way to read OneNote content via REST APIs using a consumer (personal account)

**Comment by rayluo** [comment]
* Hmm, it is always good to test it out. The device flow was said to NOT work for Microsoft account (according to the last bullet point of [this section](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-supported-account-types#account-type-support-in-authentication-flows)), but your latest attempt went further than that already.
* Would you mind to try again and see if you still see that error? I tried several times just now. At a point I saw intermittent error FROM MY BROWSER after I login and consent (but that was still DIFFERENT than your `HTTPError: 503 Server Error` above). In my recent attempts, I am able to get a token back. That is yet another step further than your last attempt.
* Device Flow is not a bad choice. Your comment "this is not the best way" was presumably because our web UI forces you to login and consent every time. That part is unfortunate, but, once you get the end-to-end flow working, you can then follow our existing [hint to cache your tokens](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.3.0/sample/device_flow_sample.py#L37-L39), so that you won't need to be typing password every time.
* Hang on. Almost there. :-)

**Comment by 1001QAdotNET** [comment]
yes this time it worked
I also had good results with using this getting a token with the code below
What is the difference between this url used below and the graphone? Old API vs new API?

```
https://login.live.com/oauth20_authorize.srf?client_id=bxxxx&scope=office.onenote_update&response_type=token&redirect_uri=http://localhost")
and then using this
headers = {"Authorization" : "Bearer " + token} 
**url="https://www.onenote.com/api/v1.0/me/notes/notebooks/"**
r=requests.get( url=url,headers = headers)
response=r.json()
notebooks=response['value']
for notebook in notebooks:
    print(notebook['name'])
    print(notebook['self'])
    print(notebook['sectionsUrl'])
    print(notebook['sectionGroupsUrl'])
```

There seem to be issues with the /pages endpoint.
I am trying to access a shared notebook, it is practically the same notebook that was shared by the personal account and it is share with my user at work. 
I can only see two old pages ...I am reading StackOverflow and there seems to be lots of problems with this endpoint. Is there anything going on currently?

**Comment by rayluo** [comment]
> yes this time it worked

I believe you mean the Device Flow worked. Yay.

> I also had good results with using this getting a token with the code below
> Get a token using this link:
>
>     https://login.live.com/oauth20_authorize.srf?client_id=bxxxx&scope=office.onenote_update&response_type=token&redirect_uri=http://localhost")

I believe you mean you use a different flow, so-called Auth Code Flow. And yes, it will also work for you to obtain a token.

> What is the difference between these endpoints? Old API vs new API?
> `url="https://www.onenote.com/api/v1.0/me/notes/notebooks/"`
> vs `https://graph.microsoft.com/v1.0/me"`

Your second URL does not seem to be a comparable endpoint to your first one. Was it a copy-and-paste error?
Regardless, at this point, I think you already accomplished the token acquisition challenge. :-)  Any different behaviors from different OneNote endpoints would be a OneNote area topic. Personally I did not try that part before. I'm looping in our PM @navyasric to see if she can shed some light here, and/or guide you to post a new question in a proper place in OneNote community.

**Comment by 1001QAdotNET** [comment]
**Thank you very much for all the above!** Yes it was a copy and paste error. 
Yes I do need to ask OneNote related questions, both authentication methods seem to end in the same dead point, OneNOte wise so I am not sure if it is a scope or another type of issue here, I can't see all my pages

**Comment by 1001QAdotNET** [comment]
Hi Navya (@navyasric)
Do you have any idea where I could post a question about why I can't see the full list of pages created in a onenote section?
This is a shared notebook, created by my home user and pages are mostly created from work where I opened the notebook by using a link that I sent to myself at work

**Comment by 1001QAdotNET** [comment]
Grrr...after struggling with this I found a wrapper https://github.com/GearPlug/microsoftgraph-python

**Comment by rayluo** [comment]
Did you mean that such a wrapper helped you solved the "unable to read OneNote pages" issue?
Previously I assumed it was an incorrect scope and/or incorrect endpoint issue, but if it was all about how to properly parse the network I/O kind of thing, Azure does provide an official Azure SDK for Python. Just so you know.

**Comment by navyasric** [comment]
@1001QAdotNET Sorry for delay. Based on the Stackoverflow post you shared initially about your scenario, it looks like you want to access the OneNote pages from a Python command line script. My understanding is that you don't need a user identity to sign in for this and you just want to access OneNote API as the Python app to do some processing. Can you confirm this?
If that is the case, you can use the [client credential flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview) with your app registered on Azure AD.  Here is a [sample](https://github.com/Azure-Samples/ms-identity-python-daemon).  The device code and auth code flow are useful if you need to sign in the user identity. 

Next, you can access the OneNote API directly or through the MS Graph. Please take a look at the [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and docs to see if the API you want to access is available through MS Graph. For further questions on MS Graph or OneNote APIs, you can post on Stackoverflow with those tags or open issues on their docs/repos.

Please let us know if this new information is helpful or I misunderstood your requirements. Thanks.

**Comment by 1001QAdotNET** [comment]
Hi @navyasric 
Thanks for the above. I will give the client credential flow once I am convinced that OneNote has  viable APIs ..
So far I have been able to use the device flow and get access to my notebook and my sections.
The problem is that I can;t get a complete list of the pages that I have in a section.
I posted a question on StackOverflow but not luck so far  https://stackoverflow.com/questions/61842075/what-is-the-reason-why-the-onenote-apis-wont-return-all-the-pages-in-a-notebook The post has ms-graph-onenote tag and the onenote-api tag as wel. No answer so far. Same for a similar question posted 3 months ago by another user. That user also went to a great lenght to have his question answered but he has had no luck. I found him on tweeter as well ..same result.  https://stackoverflow.com/search?q=onenote+api+lag and see this https://twitter.com/_DarrenCohen/status/1234848210423894016 (this guys is trying to help him)

So not sure how posting on StackOverflow will be of any help. 

Anyway, to circumvent the above I used a trick...I created a brand new Section and In order to test the API I moved a sample page there and that is returned ...it is the only one there how could it be missed ...and now I am struggling with updating that page and I am getting another strange error:

We are already way off topic here but it is really discouraging to see how difficult it is to get support. Everything is being pushed toward Azure Cloud and MS Grah but the whole thing becomes a real nightmare for a regular user (MS Account) and for a less trained user who has no idea about Azure Cloud, Azure AD and all that. 

```
{
  "error": {
    "code": "UnknownError",
    "message": "{\r\n  \"Message\": \"No HTTP resource was found that matches the request URI 'https://www.onenote.com/api/v1.0/users('allsortofquestions@yahoo.com')/notes'.\"\r\n}",
    "innerError": {
      "request-id": "ee9fa487-288a-4dc7-ba3a-9a92cb9102f9",
      "date": "2020-05-18T14:25:47"
    }
  }
}


```

**Comment by darrelmiller** [comment]
The docs for how to access OneNote content via Microsoft are here https://docs.microsoft.com/en-us/graph/integrate-with-onenote

The `https://www.onenote.com/api/v1.0/me/notes/notebooks/` is the old API that we no longer recommend. This `https://login.live.com/oauth20_authorize.srf?client_id=bxxxx&scope=office.onenote_update&response_type=token&redirect_uri=http://localhost")` endpoint is for the old API and should not be used to access Microsoft Graph.

Some of the StackOverflow messages you pointed to about OneNote pages not returning completely like [this](https://stackoverflow.com/questions/59637838/onenote-api-pages-endpoint-not-working-properly) has an answer from a Microsoft engineer saying the problem was resolved and a SO moderator "helpfully" deleted it because it duplicated an answer to other questions.

The documentation to [get a list of pages](https://docs.microsoft.com/en-us/graph/api/onenote-list-pages?view=graph-rest-1.0) includes the permissions that need to be consented to in order for your app to be able to read that content.

**Comment by 1001QAdotNET** [comment]
Hi @darrelmiller 
The above is in essence a recap of what I have tried to do and how  got where I am today. As explained on SO I am using this Python  code to get a token

   ```
 tenant = "5fae6798-ca1a-49d4-a5fb-xxxxx"
    client_id = "d03a79d3-1de0-494c-8eb0-xxxxxxx"
    from msal import PublicClientApplication
    import requests
    endpoint= "https://graph.microsoft.com/v1.0/me/onenote"
    authority = "https://login.microsoftonline.com/consumers"
    app=PublicClientApplication(client_id=client_id, authority=authority)
    flow = app.initiate_device_flow(scopes=scopes)
    # there is an interactive part here that I automated using selenium, you 
    # are supposed to ouse a link to enter a code and then autorize the 
    # device; code not shown
    result = app.acquire_token_by_device_flow(flow)
    token= result['access_token']
    headers={'Authorization': 'Bearer ' + token}
    endpoint= "https://graph.microsoft.com/v1.0/users/c5af8759-4785-4abf-9434-xxxxxxxxx/onenote/notebooks"
    notebooks = requests.get(endpoint,headers=headers).json()
    for notebook in notebooks['value']:
        print(notebook['displayName']) 
        print(notebook['sectionsUrl']) 
        print(notebook['sectionGroupsUrl']) 
    # After that I pick a certain notebook 
    section=[section for section in sections if section['displayName']=="Test"][0]
    endpoint=notebook['sectionsUrl']
    pages=requests.get(endpoint,headers=headers).json() 

    for page in pages['value']:
        print(page['title']) 

```

The problem is that I am not receiving all the pages in the sections
Ex:
If I use this endpoint
https://graph.microsoft.com/v1.0/users/user-id/onenote/sections/section-id/pages
I would expect to get the complete list of pages for that section.
That is not working

After reading again and again the docs I my understanding is that the approach is to 
call https://graph.microsoft.com/v1.0/users/user-id/onenote/pages$**filter or search etc etc**

Is there a guide for using OData searches, specific to OneNote?

Are the above correct?
Also I vaguely remember there is a way to search for a section and have it expanded so that the search returs the children too. 

Am I close to understanding this?

**Comment by rayluo** [comment]
Hi @1001QAdotNET, this thread grew long and became hard to keep track. Am I understanding correctly that your original question of this very issue has been addressed, according to [your acknowledgement here](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/194#issuecomment-629569242) and your [now-closed original question in StackOverflow](https://stackoverflow.com/questions/61803191/what-type-of-app-authentication-flow-should-i-select-to-read-my-cloud-onenote-co)? If so, I would suggest to close this issue here, and then you can keep your OneNote-relevant topic in the other issue #201 open. What do you think?

**Comment by 1001QAdotNET** [comment]
es I agree this was solved, thank you again for helping me
I will close it, if you need to clean it up please go ahead
