### ISSUE TITLE
offline_token allways requested?

### ISSUE THREAD

**Issue by cblomart** [AzureAD/microsoft-authentication-library-for-python#207]
Hello, 

I am looking at the flask sample.

It seems like offline_access is requested by default, is there any way to disable that?

In the context users of the application would be reassured not to see:
"Maintain access to data you have given it access to"

Cédric

**Comment by rayluo** [comment]
Hi Connor, thanks for your excellent question! You even did your homework and found our sample's upstream repo (here) to ask it.

We understand your point about hoping to avoid displaying "Maintain access to data you have given it access to". However, that is not possible in this MSAL library, as MSAL has been designed to always require `offline_access`.

Out of curiosity, are you trying to only sign in an end user, without acquiring an access token to call a different web api?

**Comment by cblomart** [comment]
Hello @rayluo 

Thanks for the fast answer.

As we all know it is not just not displaying the message. Specialty if this is the case.

If I understand well, requesting [``offline_access``](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#offline_access) scope will provide a long term refresh token.

That doesn't mean that I don't require an access_token! The access token would be used to make different queries to graph API. I just don't need it in the long term and don't want to worry users (as some does adequate what an app does and what rights it requires).

Cédric

**Comment by rayluo** [comment]
> Thanks for the fast answer.

You bet. :-)

> As we all know it is not just not displaying the message

Understood. I did mean to say it is about the security perception behind that message.

> If I understand well, requesting [`offline_access`](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#offline_access) scope will provide a long term refresh token.
> 
> That doesn't mean that I don't require an access_token! The access token would be used to make different queries to graph API. I just don't need it in the long term and don't want to worry users (as some does adequate what an app does and what rights it requires).

Your understanding is correct. Unfortunately MSAL has been hard coded to require `offline_access`. If you send me private message in email, I can further explain this.

**Comment by ibauersachs** [comment]
Always requesting offline_access is a security issue. Why should an app that doesn't require it request this scope? Please remove it or at least make it configurable!

**Comment by CPonchet** [comment]
Hi @rayluo,

Thanks for your feedback, is it possible to get more information regarding the reasons to force the offline_access scope, please? I noted the android and iOS library do the same actually.

Because of this behaviour (an issue for us), we stop using the python MSAL since June because of conditional access possibilities (and I would love to use it again).

For classic situation, conditional access is well managed in adding the missing scope into the authorize request. Some tricky setup can forbid the token generation.

Indeed, the conditional access may impact the [Graph resources](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/microsoft-365-policies-configurations?view=o365-worldwide#deployment-and-your-apps) directly in not giving access to the whole graph for the offsite situation for instance.
In this case, Office 365 resources are not accessible, so the token can not be generated. That is to say, we block all the SSO and login operations because of token generation. When the _profile_ or _email_ and _openid_ scopes may be enough for the user to log in to our application, there are no possibilities except using other libraries. A point which is a little annoying regarding integration and seems not really future proof ready with AAD restrictions/conditional access.

Do you have any idea about:
* If it will be available in the coming month?
* If it will stay as it is?

Many thanks in advance :)

**Comment by navyasric** [comment]
Hi @CPonchet  The reason MSAL adds the offline_access scope by default is to ensure we get a refresh token that can be used to keep refresh the tokens and maintain SSO in the app. We notice that in most cases apps prefer to maintain SSO and keep the user signed in without having to prompt them repeatedly. 
Do you have scenarios where you don't need to keep the user signed in or you don't need to refresh access? Can you explain the user auth scenario?

For handling conditional access, please take a look at this [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Conditional-Access-and-Claims-Challenges) page. Are you handling the CA challenge this way?
It is not clear to me why this is blocking login and SSO for you? Are you saying you have scenario where you only want ID token without an access token for resource?

**Comment by rayluo** [comment]
@cblomart @ibauersachs  @CPonchet 
Thank you all for your patience. This topic of "do not always request offline_access" turns out to be very tricky. I want to give an update on the recent progress. There are 2 aspects.

1. The client-side. MSAL Python will soon provide a parameter for you to configure opting out of `offline_access`. So your app would operate in the "least-privilege" mode that you desire. You can try this new parameter, by installing the feature branch directly from our github repo `pip install git+https://github.com/AzureAD/microsoft-authentication-library-for-python.git@remove-offline-access` and let us know your test result. (such a preview command will become invalid after we merge in that feature branch in next few days).
2. The service-side. Currently, even when your MSAL-powered app opts out of `offline_access`, the Microsoft identity platform (Azure ActiveDirectory) consent page will probably still show the sentence "Maintain access to data you have given it access to", due to historical reasons. Our team will work on this. Despite of such a UX issue, your app using the feature mentioned in `(1)` above would indeed operate in a least-privilege mode.

**Comment by CPonchet** [comment]
Many thanks @rayluo :)
