### ISSUE TITLE
Add support for extraScopesToConsent

### ISSUE THREAD

**Issue by navyasric** [AzureAD/microsoft-authentication-library-for-python#212]
Add support for consent to multiple resources upfront. More details [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#have-the-user-consent-upfront-for-several-resources)

**Comment by rayluo** [comment]
Quick triaging thoughts for future reference:
* Historically this feature is only implemented in `acquire_token_interactive(...)`, which is not currently available in MSAL Python until we implement #138 first.
* The name `extraScopesToConsent` is long, and it would be even longer in Python because of Python's conventional snake case `extra_scopes_to_consent`. Back then, when the cross-libraries (including .Net, Python, etc.) discussion happened with PM (Vittorio), the conclusion was to use a short name `additional_scope` (or `additional_scopes`). [Such a word choice has long been documented inside MSAL Python's code base](https://github.com/AzureAD/microsoft-authentication-library-for-python/blame/1c6832b2c58ee34f8e5c9f963d37cbb7a1311bb5/msal/application.py#L132-L137) since 4 years ago.

**Comment by danieluct** [comment]
Any suggestion how to get consent for multiple scopes in device workflow without requiring user to enter multiples codes?

**Comment by rayluo** [comment]
@danieluct Were you talking about the [Device Flow? Its `scopes` parameter accepts a list of multiple scopes](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.initiate_device_flow). We might not specifically test such combination, so feel free to let us know if that does not work - but that would probably be in a new issue.
