### ISSUE TITLE
Implement ADFS authority validation

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-python#213]
Please read ADFS authority validation [spec](https://microsoft.sharepoint.com/:w:/r/teams/aad/devex/_layouts/15/Doc.aspx?sourcedoc=%7BF0EB0F6F-2B78-42A2-B44F-01DA1D6015E2%7D&file=ADFS%20Authority%20Validation%20-%20Original%20Spec.docx&action=default&mobileredirect=true&wdLOR=c22AE0924-0124-3D40-8BD4-435F36B291C7&cid=55F6763D-6E90-4588-A0AD-AF062981A3E4) and asses if MSAL java implements this. 

Please see equivalent MSAL.NET [issue ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1885)for a few more details.

As discussed with @henrik-me

**Comment by rayluo** [comment]
@bgavrilMS , is this issue still relevant? The referenced [MSAL .Net issue mentioned](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1885#issue-637872473) "Expected behavior
ADFS authority validation should perform a discovery call to a global endpoint" but was later [closed without any change](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1885#issuecomment-689027835).

Besides, based on our recent discussion on the generic Authority Validation topic, we are moving away from authority validation for ADFS (by replacing it with `known_authorities` behaviors).

I think we can close this issue now.
