### ISSUE TITLE
WS-Trust Request Fails because of casing issue in XML body

### ISSUE THREAD

**Issue by jlodom** [AzureAD/microsoft-authentication-library-for-python#228]
I include the fix for this towards the bottom -- very simple.

**Describe the bug**
When sending a WS-Trust request to some 3rd-Party Federations, message fails because of improper casing in MessageID

**To Reproduce**
(You are not expected to do this.)
Set up a WS-Trust relationship with a product like NetIQ Access Manager and then use MSAL to authenticate using a method like "acquire_token_by_username_password"

Error returned from Access Manager is:
"A required header representing a Message Addressing Property is not present, Problem header:{http://www.w3.org/2005/08/addressing}MessageID"

To Fix: On line 82 of wtrust_request.py , 
change:
<wsa:messageID>urn:uuid:{message_id}</wsa:messageID>
to:
<wsa:MessageID>urn:uuid:{message_id}</wsa:MessageID>
(i.e. just capitalize the "m" in "MessageID")

**The MSAL Python version you are using**
1.4.1

**Additional context**
The error is actually happening in Sun's XML parsing libraries, so other products doing WS-Trust in Java may be affected.

**Comment by rayluo** [comment]
@jlodom  Thanks for bringing this to our attention.

This is also an implementation MSAL Python inherits from its predecessor, ADAL Python, and [ADAL Python had that this way since day 1](https://github.com/AzureAD/azure-activedirectory-library-for-python/blame/ff9a0ade66d810421b47cee73c88555527c1bb83/adal/wstrust_request.py#L77).

Now taking a close look, that element seems [supposed to be `MessageID`](https://www.w3.org/2006/03/addressing/ws-addr.xsd), and yes [XML is case sensitive](http://xml.silmaril.ie/case.html). But that would also mean when/if we change its case this time, it would technically be a breaking change.

@abhidnya13 Please help investigate similar implementation in our other ADAL/MSAL libraries to give us a full picture.

**Comment by jlodom** [comment]
Ha ha, yes I am the master of obscure edge cases here -- how many folks are
likely to use AzureAD+Python+NetIQ Access Manager? But I am likely to be
using it a lot in the near future (even giving a presentation involving it
later this week).  Thank you for taking this seriously, and I look forward
to seeing what your investigation yields.

**Comment by abhidnya13** [comment]
I happened to check the implementation of [MSAL Java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/ca87b927f249f7dd00bb422be255137409cbe492/src/main/java/com/microsoft/aad/msal4j/WSTrustRequest.java#L141) and [MSAL .NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/1cef43d185bb0a1dcc013d2ec232ae9d4c6c053a/src/client/Microsoft.Identity.Client/WsTrust/WsTrustEndpoint.cs#L83) library and both seem to be using `messageID`. Although its interesting to see the link @rayluo mentioned which mentions the use of `MessageID` in the spec. 

Also a quick change to use `MessageId` in the MSAL Python implementation makes our e2e test case for federated scenarios to fail. So we will have to dig deeper into what spec the services follow and what is expected here.

**Comment by rayluo** [comment]
@abhidnya13 Out of curiosity, what was the failure message you saw? Can you tentatively create a branch with that change, and then share a link to its test automation result?

**Comment by abhidnya13** [comment]
I was getting a parse error, but then I made a change which I was missing in my previous implementation change and now it works fine as in the test which was previously failing now passes. I'll create a branch and make sure the automation there passes as well. and update my comment here.
