### ISSUE TITLE
The OAuth2 client violates the RFC 6749 spec for Basic Auth when encoding client_id & password

### ISSUE THREAD

**Issue by schlenk** [AzureAD/microsoft-authentication-library-for-python#231]
**Describe the bug**
RFC 6749 states in 2.3.1 that the client_id and password must be URL encoded before being base64 encoded.
(also see the errata https://www.rfc-editor.org/errata/eid4749 which clarifies it).

The current code in oauth2.py does not do the urlencoding step as far as i can see:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0ced4cb65f5a58c748c5792ddd428e2ef8000866/msal/oauth2cli/oauth2.py#L208

**Comment by rayluo** [comment]
Thanks for the nice finding! Out of curiosity, you were just doing a code review, weren't you? Your existing confidential app powered by MSAL still works, doesn't it?

**Comment by schlenk** [comment]
It got mentioned in a bugreport for https://github.com/OpenIDC/pyoidc/issues/754 and as we decided that we were spec compliant there, i reported it here. So this might actually be buggy on the Azure server side too, did not try with a proper client_id/secret that needs to be quoted.

**Comment by rayluo** [comment]
OK then. For the record, Microsoft identity system is not susceptible to this tricky issue, because:
* client_id and client_secret generated by Azure AD does not contain special characters, so that encoding would be a no-op anyway.
* This MSAL Python library runs a different code path.

We will still make some change to make our code base conceptually right, but our existing customers would not be affected by this.

**Comment by rayluo** [comment]
Fixed. Again, this does not affect our existing customers.
