### ISSUE TITLE
[Fundamentals] Rename master branch to main

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-python#277]
**Main branch**
_An inclusive new default_
New repos created within Microsoft orgs now have the default branch name of 'main'.

Teams are encouraged to rename their default branches if they are still using the 'master' branch name. This is an important, but not urgent, change.

**See more:**
https://repos.opensource.microsoft.com/

**Comment by rayluo** [comment]
OK. Also quoting a couple more relevant info on this topic: [a discussion in GNOME modules](https://mail.gnome.org/archives/desktop-devel-list/2020-June/msg00023.html), and [similar changes in Python](https://bugs.python.org/issue34605).

We will need some 2, 3 releases to test out this change, because the existing release tooling hardcode the major branch name.

**Comment by rayluo** [comment]
Done. The latest release, [1.7.0, has been released from the new `main` branch](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/284), and the release automation runs [successfully](https://pypi.org/project/msal/1.7.0/).
