### ISSUE TITLE
Authorize python flask web application users to call protected web API based on their defined roles

### ISSUE THREAD

**Issue by sanakanchha** [AzureAD/microsoft-authentication-library-for-python#292]
I have a python flask web application(client) and a .net core web api application where the python flask application signs in user with Azure AD credentials and then calls the .net api

Authentication:
I used this library to set up Azure AD authentication to call the protected .net web API which has been working great.

Authorization:
Now, I have defined and implemented the RBAC roles(eg. admin) for the .net web api so that users with certain roles would have access to certain apis. However I get a 403 unauthorized while calling the API  even though the jwt token generated has the correct scopes.

Does this library provide this capability? Could you please let me know?

**Comment by rayluo** [comment]
> Authentication:
> I used this library to set up Azure AD authentication to call the protected .net web API which has been working great.

But if your flask app can call your protected .net web API, the authorization is already working. Then what did you mean by "However I get a 403 unauthorized while calling the API even though the jwt token generated has the correct scopes"?

Regardless, I would suggest you to `print(my_api_call_response.text)` to see if there were any human-readable error message, for your troubleshooting. If the issue was indeed caused by your access token was rejected, you would most likely need to double check what scope your .net web api was defined/required.

FWIW, we have a working flask web app sample [here](https://github.com/Azure-Samples/ms-identity-python-webapp).

**Comment by sanakanchha** [comment]
@rayluo Updated the libraries as in the sample and worked like a charm. Thanks for this great library.
