### ISSUE TITLE
Cannot import msal on Python 3.8.5

### ISSUE THREAD

**Issue by AntoineWeber** [AzureAD/microsoft-authentication-library-for-python#311]
**Describe the bug**
Whenever I try to import msal, I get the error: AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'
See the image below for exact error output.
I tried this on a brand new conda environment.

**To Reproduce**
Try to import msal on python 3.8.5

**Expected behavior**
the import to happen without errors.

**What you see instead**
![image](https://user-images.githubusercontent.com/36995487/107387564-3eea3400-6af5-11eb-9bf6-585cf012e90b.png)

**The MSAL Python version you are using**
Paste the output of this
`python -c "import msal; print(msal.__version__)"`
Cannot past the output since the error happens at import time.

**Additional context**
None

**Comment by rayluo** [comment]
We could not reproduce this issue. This was our [latest successful run on Python 3.8](https://github.com/AzureAD/microsoft-authentication-library-for-python/runs/1861397671?check_suite_focus=true#step:3:12), albeit on a slightly higher version.

Just to rule out possible issue. Would you check you do not have another file named `ssl.py` under the same folder? If that is not the case, you may consider to post this issue to our upstream modules, [urllib3](https://github.com/urllib3/urllib3) or [requests](https://github.com/psf/requests), since the exception was thrown from there.

**Comment by AntoineWeber** [comment]
I rolled back to python 3.7.9. There were no constraints for me to maintain python 3.8.5, hence this looked like the easiest fix.
After the roll back, I could import the library without any error.
