### ISSUE TITLE
initial configuration for use of username_passwrd_sample

### ISSUE THREAD

**Issue by henriqueweiand** [AzureAD/microsoft-authentication-library-for-python#33]
I am trying to use using msal authentication with azure active directory in the validation example per user and password. But when trying to run .py I get the following result:

![Captura de Tela 2019-04-10 às 14 25 08](https://user-images.githubusercontent.com/6539492/55899972-7952b500-5b9c-11e9-9203-e07a8d312314.png)

I believe that it does not change anything, but I made my settings inside the file itself

```
...

# Optional logging
logging.basicConfig(level=logging.DEBUG)

config = {
  "authority": "https://login.microsoftonline.com/organizations",
  "client_id": "Tenent_id",
  "username": "XXX",
  "scope": ["User.Read"],
  "password": "XXX"
}

# Create a preferably long-lived app instance which maintains a token cache.
app = msal.PublicClientApplication(config["client_id"], authority=config["authority"])
...
```

**Comment by rayluo** [comment]
Sorry for the confusion here, but by design and policy, the username/password authentication works only for Work and school accounts, but not for Microsoft Accounts (MSA). See the [definition of these 2 types of accounts here](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/sign-up-organization).

We will document this in API description and/or the sample itself, and probably also figure out how to generate a more helpful error message here, but ultimately you will have to use other authentication methods (such as, [device flow](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/0.3.0/sample/device_flow_sample.py)) with your personal MSA account.
