### ISSUE TITLE
What is the telemetry for?

### ISSUE THREAD

**Issue by Moult** [AzureAD/microsoft-authentication-library-for-python#353]
Looking at #175 and #137 seem to hint that there is some internal Microsoft specification for telemetry. Can someone confirm what is the telemetry module used for, what data is it collecting, how is it stored, and what it is used for?

**Comment by rayluo** [comment]
The telemetry is used by Microsoft to monitor how a library performs, so that we would be able to calibrate and improve the library in future releases. Those internal Microsoft specification is just some schema details about the data format. To our customers, what you care most would probably be what it collects. This is easy to verify for such an open source library. What we collect are: ["which API/function you call", "whether MSAL effectively helps you refresh an expiring token"](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.11.0/msal/telemetry.py#L41-L42), and also ["did your API calls succeed", "what error occurred"](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.11.0/msal/telemetry.py#L51). Here I want to emphasize that, none of the data above is Personally identifiable information (PII).

**Comment by Moult** [comment]
Thanks for the clarification.
