### ISSUE TITLE
[Feature Request] MSAL Python supports Prompt.Create so that customers can implement self-service sign-up

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-python#356]
_**Note:** [MSAL.NET work item](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2463), was completed and can be used as reference implementation._

**Is your feature request related to a problem? Please describe.**
When developers want to implement self-service sign up for their apps, they can use a `prompt=create`, triggered by a "Sign-up" link in their app. The end user can then enter the 'create account' experience.

**Describe the solution you'd like**
MSAL.NET should propose a new property named `Create` in the `Prompt` class. When using this property, MSAL.NET would send 'prompt=create' to the authorize endpoint, which will trigger the sign-up experience.

**Additional context**

Example URL:
https://login.microsoftonline.com/d014fd44-d398-4813-a3a9-8cd725f7f356/oauth2/authorize?
client_id=da53de5a-636b-425f-ad57-0f62d6f974c7
&response_type=id_token
&resource=da53de5a-636b-425f-ad57-0f62d6f974c7
&scope=openid
&nonce=default_nonce
&redirect_uri=https://jwt.ms
&prompt=create

![image](https://user-images.githubusercontent.com/13203188/110445289-3f5af800-80be-11eb-9a77-4afe34e834b5.png) 

The draft OIDC spec for this is here: https://openid.net/specs/openid-connect-prompt-create-1_0.html

**Work to do**
- [ ] Expose a new Create property in `Prompt`.
- [ ] Wire-up the prompt so that 'prompt=create' is sent to the authorize endpoint when this prompt is used.
- [ ] Update the [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withprompt), or better redirect it to the docs.ms page, which would, however need to be synced
 Update after release
- [ ] Update the docs.ms [AcquireToken desktop scenario page](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withprompt).
[MS Docs PR](https://github.com/MicrosoftDocs/azure-docs/pull/72667) Merge after release

**Comment by rayluo** [comment]
**Work to do**
- [x] ~~Expose a new Create property in `Prompt`.~~ Automatically supported in `acquire_token_interactive` etc..
- [x] ~~Wire-up the prompt so that 'prompt=create' is sent to the authorize endpoint when this prompt is used.~~ See above.
- [ ] ~~Update the [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withprompt), or better redirect it to the docs.ms page, which would, however need to be synced
 Update after release~~ Adding one more line into the existing interactive flow sample. (PR #360)
- [ ] Update the docs.ms [AcquireToken desktop scenario page](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#withprompt). This new [MS Docs PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/158244) is waiting for someone to review.
