### ISSUE TITLE
Unnecessary requests during regional STS authentication

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-python#372]
Acquiring a token from a regional authority takes a long time due to apparently redundant and/or unnecessary requests.

## Repro script
```py
import logging
from msal import ConfidentialClientApplication

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(module)s: %(message)s")

logging.info("*** creating ConfidentialClientApplication")
app = ConfidentialClientApplication(
    client_id,
    client_credential=client_secret,
    authority="https://login.microsoftonline.com/" + tenant_id,
    azure_region="eastus",
)

scopes = ["https://management.azure.com/.default"]
logging.info("*** attempting silent auth with an empty cache")
app.acquire_token_silent(scopes, account=None)

logging.info("*** acquiring a new token")
token = app.acquire_token_for_client(scopes)
```

## Output (after some tidying)
```
12:56:51 *** creating ConfidentialClientApplication
(1) connectionpool: https://login.microsoftonline.com:443 "GET /72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
(2) region: Connecting to IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01. It may take a while if you are running outside of Azure. You should consider opting in/out region behavior on-demand, by loading a boolean flag "is_deployed_in_azure" from your per-deployment config and then do "app = ConfidentialClientApplication(..., azure_region=is_deployed_in_azure)"
    connectionpool: Starting new HTTP connection (1): 169.254.169.254:80
    region: IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01 unavailable. Perhaps not running in Azure VM?
    application: Region configured ('eastus') != region detected (None)
    application: Region to be used: 'eastus'
    connectionpool: https://eastus.login.microsoft.com:443 "GET /72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1227
  
13:01:19 *** attempting silent auth with an empty cache
(3) region: Connecting to IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01. It may take a while if you are running outside of Azure. You should consider opting in/out region behavior on-demand, by loading a boolean flag "is_deployed_in_azure" from your per-deployment config and then do "app = ConfidentialClientApplication(..., azure_region=is_deployed_in_azure)"
    connectionpool: Starting new HTTP connection (3): 169.254.169.254:80
    region: IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01 unavailable. Perhaps not running in Azure VM?
    application: Region configured ('eastus') != region detected (None)
    application: Region to be used: 'eastus'
(4) connectionpool: https://eastus.login.microsoft.com:443 "GET /72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1227
(5) region: Connecting to IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01. It may take a while if you are running outside of Azure. You should consider opting in/out region behavior on-demand, by loading a boolean flag "is_deployed_in_azure" from your per-deployment config and then do "app = ConfidentialClientApplication(..., azure_region=is_deployed_in_azure)"
    connectionpool: Starting new HTTP connection (5): 169.254.169.254:80
    region: IMDS http://169.254.169.254/metadata/instance/compute/location?format=text&api-version=2021-01-01 unavailable. Perhaps not running in Azure VM?
    application: Region configured ('eastus') != region detected (None)
    application: Region to be used: 'eastus'
(6) connectionpool: https://eastus.login.microsoft.com:443 "GET /72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1227
(7) connectionpool: https://login.microsoftonline.com:443 "GET /common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize HTTP/1.1" 200 945

(8) 13:10:12 *** acquiring a new token
    connectionpool: https://eastus.login.microsoft.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token HTTP/1.1" 400 459
```
1. naively, this seems unnecessary given the subsequent regional discovery request(s)
2. I specified a region, why request location data from IMDS?
3. requesting location from IMDS again
    - side question: does `acquire_token_silent` need to send any requests? This is a confidential client with an empty cache.
4. regional tenant discovery (again)
5. requesting location from IMDS again
6. regional tenant discovery (again)
7. is this necessary given that we already completed tenant discovery and are using a well-known instance?
8. it took 13 minutes to acquire a token

**Comment by rayluo** [comment]
Thanks, Charles, for the detailed report!

1. I hear you. Your "naive" assumption is quite reasonable. In fact, before regional endpoint support was introduced in MSAL Python 1.12, you could perhaps use `app = ConfidentialClientApplication(..., authority="https://eastus.login.microsoftonline.com/" + tenant_id)`, possibly with a `validate_authority=False`, to decisively opt in to use a certain regional endpoint, and then MSAL Python won't trigger behavior (1) & (2) in your report.

   Now, to explain (1), that is because the internal regional endpoint design wants MSAL to always validate the non-regional authority first, before attempting a validation to regional endpoint.

2. This is another behavior the current design dictates. The idea is to detect the `Region configured ('abc') != region detected (xyz)` situation for the stakeholders. Unfortunately, such a detection comes with a price: potential long latency, when your application is running outside of an Azure VM.

   The majority of the latency is caused by this undesirable IMDS call. There is not much MSAL can do here, so we just provided the message inside the log *"...It may take a while if you are running outside of Azure. You should consider opting in/out region behavior on-demand, by loading a boolean flag "is_deployed_in_azure" from your per-deployment config and then do "app = ConfidentialClientApplication(..., azure_region=is_deployed_in_azure)"*.

3 & 4 & 5 & 6 & 7: OK there can be some optimization here. I'll send out an improvement PR soon. But even so, you will still have a noticeable up to 5 minutes latency, until you follow the suggestion on (2) above.
