### ISSUE TITLE
Upstream PyJWT has vulnerability issue- CVE-2022-29217 Prevent key confusion through non-blocklisted public key formats. GHSA-ffqj-6fqr-9h24

### ISSUE THREAD

**Issue by llawwaii** [AzureAD/microsoft-authentication-library-for-python#473]
**Describe the bug**
PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.

https://www.mend.io/vulnerability-database/CVE-2022-29217

Could you please upgrade pyjwt from 2.3.0 to 2.4.0 to fix the vulnerability.

**Comment by rayluo** [comment]
Hi Wai, thanks for bringing that upstream dependency PyJWT's decoding vulnerability to our attention. After examination, we believe MSAL Python's usage of PyJWT is insusceptible to this issue, because: (1) [MSAL Python only uses PyJWT for encoding](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/636a58ccb4e000335ae251cc374bdc17baa68fc2/msal/oauth2cli/assertion.py#L114), not for decoding; (2) MSAL Python already allows downstream apps to freely upgrade to latest PyJWT 2.4.0 (for example, `pip install -U pyjwt`).
