### ISSUE TITLE
Is MSAL ready for hybrid or postquantum PKI?

### ISSUE THREAD

**Issue by 3BK** [AzureAD/microsoft-authentication-library-for-python#517]
It appears that MSAL uses algorithms like RS256.  

Is MSAL ready for hybrid and postquantum PKI?  

references
https://www.ietf.org/archive/id/draft-prorock-cose-post-quantum-signatures-01.txt
https://dl.acm.org/doi/abs/10.1007/978-3-031-20974-1_20
https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

**Comment by rayluo** [comment]
> It appears that MSAL uses algorithms like RS256.

In MSAL Python code base, there is only [one occurrence of RS256](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.20.0/msal/application.py#L678), and that is only because that algorithm is recognized by the back end service. Besides, even that "RS256" code path can be skipped, if the caller provides its own assertion (again, providing that the new assertion's algorithm is recognized by the service side).

> Is MSAL ready for hybrid and postquantum PKI?

MSAL itself does not really have a preference of using one algorithm or another. We haven't tested other algorithms. Feel free to explore and let us know whether you see some improvement is desirable.

**Comment by 3BK** [comment]
Please see AzureAD/microsoft-authentication-library-for-dotnet] Is MSAL ready for hybrid and postquantum PKI? (Issue #3848).

There are several moving parts to consider.

________________________________

**Comment by rayluo** [comment]
Sure. Linking this issue to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3848

**Comment by 3BK** [comment]
It appears that other vendors are future oriented.

https://blog.chromium.org/2023/08/protecting-chrome-traffic-with-hybrid.html?m=1

https://blog.cloudflare.com/post-quantum-tunnel/

https://www.dwavesys.com/




________________________________

**Comment by 3BK** [comment]
Unless I'm mistaken, RSA(2048) has a strength of 56 bits (112/2).  And RSA(3072) has a strength of 64 bits.

By design, MSAL is supposed to have a minimum strength of 112bits (assuming the data is ephemeral.)   Likewise, MSAL is supposed to have a strength of 128bits if the data is persistent for more than 7 years.

Time to go back to MIT....

________________________________

**Comment by 3BK** [comment]
Imagine what would happen to MSAL if a cubic search algorithm was used - instead of a quadratic algorithm such as Grover's algorithm.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 3BK** [comment]
Suggest upgrading to RSA 15360 ;) or migrating away from weak algorithms such as RSA.

https://www.f5.com/labs/articles/threat-intelligence/rsa-in-a-pre-post-quantum-computing-world
________________________________

**Comment by 3BK** [comment]
To elaborate,  your cryptographers released a paper with Google, blackberry, and ibm claiming that there is a 50% chance that RSA will fail within the next 7+ years.  You have a multi-billion dollar investment in a technology which your own experts expect to fail.

To tie a bow on this: Reasonable man theory refers to a test whereby a hypothetical person is used as a legal standard, especially to determine if someone acted with negligence.

________________________________

**Comment by rayluo** [comment]
@3BK , this issue was/is currently labeled as an answered question, and it is not immediately actionable on MSAL which is a client-side library. We can revisit this, preferably when some [prerequisites](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3848#issuecomment-1341043389) are met. Meanwhile, you can keep track using that other issue where most of the conversation happened there.
