### ISSUE TITLE
Documentation/demo showing an example of running under Linux is missing

### ISSUE THREAD

**Issue by enerdev2022** [AzureAD/microsoft-authentication-library-for-python#527]
**Describe the bug**
I cannot understand whether Linux is supported in interactive mode or not. Would it launch a sign-in browser window/tab or prompt within console? Etc.

**To Reproduce**
1. Look at documentation, description, video hosting websites.
2. See no screenshots/examples of the thing actually running interactively under Linux - GUI and/or command-line.

**Expected behavior**
See a visual "proof" that it works under Linux and understand the experience users would have.

**What you see instead**
Absence of such examples as far as I can see.

**The MSAL Python version you are using**
Latest.

**Additional context**
I tried Linux Docker, but believe it just simply doesn't work: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/422

**Comment by rayluo** [comment]
> **Describe the bug** I cannot understand whether Linux is supported in interactive mode or not. Would it launch a sign-in browser window/tab or prompt within console? Etc.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Look at documentation, description, video hosting websites.
> 
>     2. See no screenshots/examples of the thing actually running interactively under Linux - GUI and/or command-line.
> 
> 
> **Expected behavior** See a visual "proof" that it works under Linux and understand the experience users would have.
> 
> **What you see instead** Absence of such examples as far as I can see.

Python is a cross-platform language. This MSAL for Python library can also be run across all major platforms that the Python can run (unless otherwise noted). So, it is normal that most of our documentation and demos mention no platform requirement. If anything, the few official statement you can find is the "Operating System" classifier in the left sidebar in [MSAL's PyPI page](https://pypi.org/project/msal/), which says "OS Independent". When in doubt, simply run [MSAL's existing samples](https://msal-python.readthedocs.io/en/latest/) on the platform you choose, and contact us if you run into any issue.


> **Additional context**
> I tried Linux Docker, but believe it just simply doesn't work: #422

In your particular case, you were not really talking about Linux, you were using Docker, which is a special topic in its own right.

I'll close this "doc/demo on Linux" issue here, and engage you in thread #422.
