### ISSUE TITLE
[Bug] _obtain_token_by_browser doesn't escape auth_uri on Linux

### ISSUE THREAD

**Issue by kceiw** [AzureAD/microsoft-authentication-library-for-python#638]
**Describe the bug**
The auth uri isn't escaped (& ampersand isn't escaped) correctly. Thus it fails to open a browser for interactive login. Below is the error message
> The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
> At line:1 char:458
> + ... fa3a53151906531f3966234ff3375c092aaaef2f74677ae26fafdf530f52&client_i ...

**To Reproduce**
1. Use this sample https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/interactive_sample.py
2. Set values in parameter.json.
   ```
   {
    "authority": "https://login.microsoftonline.com/organizations",
    "client_id": "<id>",
    "scope": [".default"],
    "username": "<email>",
    "endpoint": "https://management.core.windows.net/"
   }
   ```
4. Run it.

**Expected behavior**
The browser is open correctly

**What you see instead**
![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/1449194/de6364f8-21b3-4ad6-9749-23133589d6a8)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/1449194/afd25579-1e8e-4353-8cb3-c482d7b30365)

**The MSAL Python version you are using**
Paste the output of this
```
> pipenv run python -c "import msal; print(msal.__version__)"
1.26.0
> echo $SHELL
/bin/bash
```

**Additional context**

**Comment by rayluo** [comment]
I use Linux as my main dev box all the time, but cannot reproduce this. Can you run `python -m webbrowser www.python.org` in your console and see how that goes? I suspect it is more about the terminal setting on your Linux distro. Perhaps searching that error message would give you a better shot on finding a solution.

**Comment by kceiw** [comment]
It can open the link as `www.python.org` but that is not the issue. The issue is that for authentication it requires some parameters and `&` is used. In my debugging `xdg-open` is first tried to open the link and throw the error.

So if you try `python -m webbrowser www.python.org?a=b&c=d` or `python -m webbrowser "www.python.org?a=b&c=d", they both return error. The error message for the latter is the same as I reported in this bug.

The issue is that the auth_uri is created inside the msal library, and that has `&` in it, and that cannot be open correctly.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/1449194/d5cae4c2-64dc-4c41-b5c4-d244138804da)

**Comment by rayluo** [comment]
> So if you try `python -m webbrowser www.python.org?a=b&c=d` or `python -m webbrowser "www.python.org?a=b&c=d"`, they both return error. The error message for the latter is the same as I reported in this bug.

In my shell, the behaviors are different.
* `python -m webbrowser www.python.org?a=b&c=d` open a webpage `https://www.python.org/?a=b` in my browser. Note the missing of `c=d` part in the page being opened. And that is expected due to the normal way a shell interprets the `&`.
* By simply putting the entire url inside double quotation marks, `python -m webbrowser "www.python.org?a=b&c=d"` correctly opens a webpage `https://www.python.org/?a=b&c=d`. Again, this is normal shell behavior.

> The issue is that the auth_uri is created inside the msal library, and that has & in it, and that cannot be open correctly.

I doubt msal library (or any other url handling script, for that matter) would have to escape `&`. From those scripts' perspective, they are providing a url, and `&` is a valid character of a url.

The culprit is probably your local `xdg-open` and/or env var `BROWSER` which is configured to use some CLI tool but fails to handle command line properly.

---

BTW, when you copy & paste your console output, it is preferable that you do not paste a screenshot picture. In stead, you can paste them as text (and wrap them inside ` ``` ` and ` ``` ` when pasting on github). That way, those content will be recognized by search engines.)

**Comment by rayluo** [comment]
@kceiw , is there any update from your investigation on your xdg-open?

**Comment by rayluo** [comment]
Closing inactive issue. Feel free to reopen if you have more findings based on the previous conversation.
