### ISSUE TITLE
[Question] Invalid user attributes: _amzn-auth.login_attributes: The value of attribute _amzn-auth.login_attributes is an empty list which is not allowed

### ISSUE THREAD

**Issue by JohnBoneJones** [AzureAD/microsoft-authentication-library-for-python#660]
I ran into this error when setting up a authentication from Azure AD to AWS Cognito for a Django applications.
: error_description: Invalid user attributes: _amzn-auth.login_attributes: The value of attribute _amzn-auth.login_attributes is an empty list which is not allowed.
Here is my configuration.
![tmp_e59339aa-886d-4874-a5ef-adb9a91363c0](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/106211553/f4324c8c-7ebe-4039-aa37-89271616aa07)
![tmp_7660e035-32be-449f-9dff-4bd0c08eec76](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/106211553/120ce4da-4ed4-429b-b901-1c0ebd891861)

![tmp_aac31cbf-0b20-4888-aa4b-f66ae7af0423](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/106211553/f159f414-6546-44c1-a921-32f72db46121)
Is there anyone knows what attribute that I missed?

**Comment by bgavrilMS** [comment]
Hi @JohnBoneJones - firstly, there is a client secret in clear in the screenshot above. Please invalidate it asap.

The MSAL libraries are extensively tested with AAD, and while we do have it on our roadmap to support other Identity Providers (including Cognito), support is currently experimental. 

The error seems to occur because the authorization URI breaks some Cognito rules. MSAL helps create the authorization URI, but it's not a huge deal, you can create it yourself.

**Comment by rayluo** [comment]
Also, perhaps the error message was Cognito expecting some field and values from the token. @JohnBoneJones you can manually examine what tokens MSAL obtained for you, by pasting your tokens into https://jwt.ms and then see if you can [customize the tokens](https://learn.microsoft.com/en-us/security/zero-trust/develop/zero-trust-token-customization).
