### ISSUE TITLE
[Bug] BaseBearerTokenAuthenticationProvider.authenticate_request does not refresh token with authorization header is present

### ISSUE THREAD

**Issue by michaeldcanady** [AzureAD/microsoft-authentication-library-for-python#670]
**Describe the bug**
When authentication a request the method `authenticate_request` fails to refresh an expired JWT token.

**To Reproduce**
1. preform any graph request requiring a token
2. verify request.headers has "authorization" key
3. wait until bearer token is expired
4. you will receive the following error "unable to parse claims from response" - upstream error due to having a bad token

**Expected behavior**
once expired `authenticate_request` should retrieve a new token.

**What you see instead**
Paste the sample output, or add screenshots to help explain your problem.

**The MSAL Python version you are using**
Paste the output of this
1.26.0

**Additional context**

**Comment by rayluo** [comment]
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. preform any graph request requiring a token
> 
>     2. verify request.headers has "authorization" key
> 
>     3. wait until bearer token is expired
> 
>     4. you will receive the following error "unable to parse claims from response" - upstream error due to having a bad token

Hey, @michaeldcanady , in our bug template, the first step was "1. Go to our [off-the-shelf samples](https://github.com/AzureAD/microsoft-authentication-library-for-python/tree/dev/sample) and pick one that is closest to your usage scenario. You should not need to modify the sample." Can you share what sample you actually use, rather than just providing your high level steps? Just looking into your steps, it sounds like your app did not even attempt token refresh between your step 3 & 4. But our off-the-shelf samples should have already taken care of that.
