### ISSUE TITLE
[Feature Request] Need support for MI per request setting

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-python#683]
### MSAL client type

Confidential

### Problem Statement

In today's identity library, we allow users to specify per request settings when each time they call get_token() method. e.g., they can specify timeout, retry count, etc.

We don't expose kwargs in msal's ManagedIdentityClient.acquire_token_for_client() method which will cause behavior changes.

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/cacb0720e6dea5cbb0a44c366587f7d33785d1af/msal/managed_identity.py#L173

**Comment by rayluo** [comment]
MSAL never means to be an http-level library, so, we refrain from adding more and more http-level behaviors into our APIs.

Downstream libraries and apps can still achieve per-request timeout behavior by creating new `msal.ManagedIdentityClient` per-request, so that you can specify its timeout. That is viable, because `ManagedIdentityClient` does not have much overhead, so you can create it frequently.

**Comment by xiangyan99** [comment]
We decided to not add the per-request configuration for now.

We will revisit it once we receive customer feedback asking for the feature.

**Comment by rayluo** [comment]
Closing now. Feel free to reopen when/if the need arises.
