### ISSUE TITLE
msal does not work behind company's VPN

### ISSUE THREAD

**Issue by bikeridercz** [AzureAD/microsoft-authentication-library-for-python#694]
Friends, considering simple code from MS examples below, it does not return a response when I'm connected to company's VPN. This really makes the OpenID authentication against our EntraID from python Flask application unusable. Any idea ? Please help.

I tried to use a proxies attribute but without success (proxies={"http":"http://proxy1.xxx:8080"})

```
from msal import PublicClientApplication
app = PublicClientApplication("your_client_id", authority="https://login.microsoftonline.com/common")

```

**Comment by rayluo** [comment]
Agreed that it sounds like that VPN setup makes OpenID auth unusable. You have to somehow fix the connection issue via trial-and-error on your side. Since you have already discovered [`proxies`](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.proxies), you can try more on that direction. You probably need a proxy setup for `https`, not `http`.

**Comment by bikeridercz** [comment]
Yes, adding https proxy helped :-) Thanks.
`... proxies={"http":"http://proxy1.xxxx:8080", "https":"http://proxy1.xxxx:8080"}`
