### ISSUE TITLE
Redirect URI not configurable in code

### ISSUE THREAD

**Issue by BrianLesko** [AzureAD/microsoft-authentication-library-for-python#696]
How do you specify the redirect URI, 
after correctly setting it in Azure online under Authentication and Mobile and Desktop Applications?

Here is the code:
```
from msal import PublicClientApplication
from clientid import ID
from clientid import tenantid

client_id = ID
authority = f'https://login.microsoftonline.com/{tenantid}'
redirect_uri = 'http://localhost:8501'
app = PublicClientApplication(client_id, authority=authority)

# Acquire token
result = app.acquire_token_interactive(scopes=['User.Read'])
if not result:
    result = app.acquire_token_interactive(['User.Read', 'email'])

# Extract email address from claims
if 'id_token_claims' in result:
    email = result['id_token_claims'].get('email')
    print(f"User's email address: {email}")
```
    
    ### When redirect_uri is added as an arg to acquire_token_interactive there is this error:
    TypeError: msal.oauth2cli.oidc.Client.obtain_token_by_browser() got multiple values for keyword argument 'redirect_uri'
    ### When added to PublicClientApplication an error thrown that it does not take redirect_uri

**Comment by rayluo** [comment]
> How do you specify the redirect URI,
> after correctly setting it in Azure online under Authentication and Mobile and Desktop Applications?
> ...
> When `redirect_uri` is added as an arg to acquire_token_interactive there is this error:

You don't. [Our doc](https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.acquire_token_interactive) does NOT mention `redirect_uri` parameter, because there is none. Instead, you can find the `port` parameter there, whose description hints that you do not have to specify a port at all. In Microsoft Entra ID, you do not need to specify a port for localhost.
