### ISSUE TITLE
Cannot get Azure subscriptions

### ISSUE THREAD

**Issue by soda92** [AzureAD/microsoft-authentication-library-for-python#703]
I use the following code:

```python
import msal
import requests
import sys
import json

data = json.load(open("parameters.json"))

config = {
    "authority": f"https://login.microsoftonline.com/{data['tenant']}",
    "client_id": data["client_id"],
    "client_secret": data["client_secret"],
    "scopes": [
        "https://management.azure.com/.default",
    ]
}

app = msal.ConfidentialClientApplication(
    config["client_id"],
    authority=config["authority"],
    client_credential=config["client_secret"],
)

result = app.acquire_token_for_client(scopes=config["scopes"])


if "access_token" in result:
    print("success")
else:
    print(result.get("error"))
    print(result.get("error_description"))
    print(result.get("correlation_id"))
    sys.exit(-1)

headers = {
    "Authorization": f"Bearer {result['access_token']}"
}

response = requests.get(
    headers=headers, url="https://management.azure.com/subscriptions?api-version=2019-08-01")

if response.status_code == 200:
    print(response.content)
else:
    print(response.status_code)

```

However, I cannot get desired result:
```
success
b'{"value":[],"count":{"type":"Total","value":0}}'
```

I can get subsriptions using token captured from browser:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/24788699/20891286-29ae-47dd-a902-6826e273f569)

The permissions are already granted.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/24788699/7acd910e-280c-425e-a6db-c8b94cbe1a4c)

I tried to add ""https://management.azure.com//user_impersonation" to scope, but it fails with error:
```
AADSTS1002012: The provided value for scope https://management.azure.com//user_impersonation is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).
```

I reads about the "OBO" flow, but my app isn't supposed to need user interactions.

Ask:
Does I miss something in the auth flow or permissions?

**Comment by soda92** [comment]
Just to be complete, this is the error from the OBO flow.
"AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'https://management.azure.com' and the expected audience is '<>' or one of the Application Uris of this application with App ID '<>'(python-client). The downstream client must request a token for the expected audience (the application that made the OBO request) and this application should use that token as the assertion.

**Comment by soda92** [comment]
moved to https://stackoverflow.com/questions/78505840/cannot-get-azure-subscriptions-using-msal-and-requests-in-python-through-rest

**Comment by bgavrilMS** [comment]
Hi @soda92 - let's keep this open as a question. The MSAL team is more likely to help on GH issues than on SO questions.

**Comment by bgavrilMS** [comment]
So, if I understand correctly you want to call an Azure Resource Manager API. This API needs to be called by a service principal (denoted by the app + secret) not by a user. OBO is indeed used for user flows (for client calls web api which calls another downstream api).

For service principal authentication, you correctly use the `acquire_token_for_client` API. The scope in this case is always the `resource\.default` so `https://management.azure.com/.default` is correct. 

So I think you have an AuthZ problem, because AAD does issue an app token back to you for ARM. However, after authenticating the service principal (denoted by the app + secret), ARM does not seem to populate the response as you expect. Most likely because you need to configure RBAC. 

I see that you are getting some help in SO with RBAC and AuthZ. Please post back if a solution is found. Thanks!

**Comment by soda92** [comment]
It was solved in SO. I will post the answer here later

**Comment by soda92** [comment]
I granted the `Reader` role for the application in the subscription, then it works

![image](https://github.com/AzureAD/microsoft-authentication-library-for-python/assets/24788699/27319c4e-efa8-4f63-bdd8-baa58c6bf56c)

Note that the app was not shown by default, we need to **enter application name in the search bar**
