### ISSUE TITLE
[Feature Request] Support for custom headers in PublicClientApplication and ConfidentialClientApplication

### ISSUE THREAD

**Issue by Joshwlks** [AzureAD/microsoft-authentication-library-for-python#734]
### MSAL client type

Public, Confidential

### Problem Statement

Currently, the `PublicClientApplication` and `ConfidentialClientApplication` classes in the MSAL Python library do not accept headers as a keyword argument. This limitation makes it difficult to add custom headers to requests, which is necessary for certain use cases such as accessing Azure environments with conditional role based access policies that require specific devices to be present in the `User-Agent` header field.

### Proposed solution

Enable a `headers` argument for both the `PublicClientApplication` object and the `ConfidentialClientApplication` object. Many thanks.

**Comment by Joshwlks** [comment]
If people agree, I would be happy to create a PR and contribute the change.

**Comment by rayluo** [comment]
In general, this library aims to provide higher and higher level of APIs to enable scenarios, rather than encouraging/forcing app developer to know the on-the-wire level of details such as "this feature needs this extra header and that special query parameter".

> add custom headers to requests, which is necessary for certain use cases such as accessing Azure environments with conditional role-based access policies that require specific devices to be present in the `User-Agent` header field.

Can you elaborate the scenario? Are there any docs that describing that protocol? Forging `User-Agent` header feels like an unusual practice, to say the least.

**Comment by Joshwlks** [comment]
Thanks for responding.

The Azure environment I am authenticating to has a conditional access policy that only allows Windows devices access. If I try to access the environment using this library's device code flow method it fails on this conditional access policy. 

I wrote a powershell script that successfully authenticates with device code flow to the same environment without using the MSAL library. The `User-Agent` in the header coming out of that powershell script is automatically being set to `Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19044; en-GB) PowerShell/7.4.5`. Looking at the `User-Agent` header in this library I can see that it is being set to `python-requests/2.25.0`.

A colleague spoke to Microsoft about this issue and they agreed that the conditional access policy cannot detect what type of device is trying to login because of the lack of information in the `User-Agent` header.

I will try to find some docs describing the conditional access policy.

**Comment by rayluo** [comment]
> A colleague spoke to Microsoft about this issue and they agreed that the conditional access policy cannot detect what type of device is trying to login because of the lack of information in the `User-Agent` header.

Information inside `User-Agent` is unreliable in the first place, because it is so easy to be forged, as you already discovered. A policy based on `User-Agent` is therefore unreliable, too.

> The `User-Agent` in the header coming out of that powershell script is automatically being set to `Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19044; en-GB) PowerShell/7.4.5`. Looking at the `User-Agent` header in this library I can see that it is being set to `python-requests/2.25.0`.

As you mentioned, that powershell script got that User-Agent value by default, it probably does not allow you to adjust that value, either. It is just that the default value happens to work. Regardless, "faking a user-agent" is hardly a feature. Similarly, this MSAL Python library got that default User-Agent value from a dependency library `requests`, and not really provides - nor do we intend to provide - an official api to alter the User-Agent.

For the sake of completeness, though, this library allows [customizing the entire http client](https://msal-python.readthedocs.io/en/latest/#msal.ClientApplication.params.http_client) to accept any `requests`'s `Session`-like object. So, you could provide your own http client with your hard-coded user-agent, if you are so inclined. Other than that, I doubt we would ever see a `user_agent` parameter in MSAL Python's API.

**Comment by Joshwlks** [comment]
Many thanks - I will look into why the policy is based on `User-Agent` as I do agree this seems strange given its unreliability. Closing this issue for now.
